version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - MONGO_URI=mongodb+srv://nicki:gatito0691.@cluster0.sxitpsr.mongodb.net/proyecto-node2?retryWrites=true&w=majority&appName=Cluster0
    depends_on:
      - mongo
    volumes:
      - ./backend:/app/backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
