version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb+srv://nicki:gatito1306.@cluster0.mongodb.net/proyecto-node2?retryWrites=true&w=majority
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
